[package]
name = "datasheet_creator"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
egui_extras = "0.31.1"
html2pdf = "0.8.2"
regex = "1.11.1"
rfd = "0.15.3"
ron = "0.8.1"
serde = {version = "1.0.218", features = ["derive"]}
tera = "1.20.0"
